codemod-com/intuita-vscode-extension

- README.md
- package.json
- src/configuration.ts
- src/extension.ts
- src/telemetry/telemetryService.ts
https://linear.app/intuita/issue/INT-338/enable-telemetry-in-the-vscode-extension
Changes:
* check if the user wants telemetry to be sent + add the telemetry settings into the extension config
* add a README info on telemetry
* timeout telemetry requests to 5000ms
> Enable telemetry in the VSCode Extension

- src/components/engineService.ts
- src/components/noraCompareServiceEngine.ts
https://linear.app/intuita/issue/INT-350/fix-spawn-working-with-spaces
Changes:
* use quotes in executable paths and pass shell:true to spawn
> INT-350 allow spaces in executable paths

- package.json
- src/components/engineService.ts
- src/components/informationMessageService.ts
- src/components/messageBus.ts
- src/extension.ts
- src/recipes/codecs.ts
- src/telemetry/telemetryService.ts
- src/utilities.ts
https://linear.app/intuita/issue/INT-374/[deployment]-ability-to-run-a-set-against-a-target-folder
Right click on a directory in the explorer view and select "execute recipe within a path"
Now, select a codemod set (recipe) to execute:
The codemod set will then execute over the provided directory (path).
> Execute recipe over a directory

- src/components/engineService.ts
- src/extension.ts
https://linear.app/intuita/issue/INT-748/[ide-ext]-display-warning-message-if-no-imported-mod-exists-and-user
> [IDE ext.] Display Warning Message if no imported mod exists and user tries to execute "imported mod on path" + do not execute

- src/extension.ts
Follow-up of https://linear.app/intuita/issue/INT-746/[ide-ext]-create-navigation-for-executing-recipe-on-path
> Add string `'v'` next to version in navigation

- package.json
- src/components/webview/MainWebviewProvider.ts
- src/elements/buildCaseElement.ts
- src/elements/buildFileElement.ts
- src/elements/types.ts
- src/extension.ts
> - Allow user to explore by folder in Codemod-first breakdown
> - Consequently, we no longer display the list of individual jobs under each case
> New design is:
> - For each case, there is a root folder with subfolders. 
> - Each folder has "Commit" / "Discard" button.
https://user-images.githubusercontent.com/32841130/233623062-7e7bb585-e5ce-4a45-b050-d02b6b9b8d96.mov
> Explore by folder in Codemod-first breakdown

- src/components/engineService.ts
- src/components/jobManager.ts
- src/extension.ts
Changes:
* add `mode` to the execution object
* add `jobs` to the execution object
* `acceptJobs` when the execution's mode was dirty-run
> INT-862 save jobs in the execution object

- intuita-webview/src/jobDiffView/App.tsx
- intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
- intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
- src/components/webview/DiffWebviewPanel.ts
As a result, we scroll into the top of the diff view more precisely than before.
> Scroll into header of diff view rather than its body on selecting file in "Change Explorer"

- intuita-webview/src/jobDiffView/App.tsx
- intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
- intuita-webview/src/jobDiffView/DiffViewer/Diff.tsx
- intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
- intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
- intuita-webview/src/jobDiffView/DiffViewer/index.tsx
- src/components/jobManager.ts
- src/components/webview/DiffWebviewPanel.ts
- src/components/webview/WebviewPanel.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
- store staged jobs state outside of webview (fixes checkboxes state lost when reopening diff view)
- do not collapse/expand job when checkbox clicked
- remove unused code
> fix job staging, fix apply 'copy' codemod

- intuita-webview/src/codemodList/TreeView/Tree.tsx
- intuita-webview/src/codemodList/TreeView/index.tsx
https://linear.app/intuita/issue/INT-919/provide-the-uri-to-select-a-specific-codemod-in-public-registry-in-the
To support opening arbitrary codemods from the URI, we need to control the opening state of tree items already at the tree view level.
This means that the `Tree` component is stateless now and no longer memoized.
> INT-919 central management of opened IDs

- intuita-webview/src/codemodList/App.tsx
- intuita-webview/src/codemodList/TreeView/index.tsx
- intuita-webview/src/sourceControl/App.tsx
- src/components/messageBus.ts
- src/components/webview/CodemodListProvider.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
Changes:
* the state in the tree view is controlled using a reducer that contains the focusedId and openedIds with two actions: flip and focus
* the URI handler passes information to the webview using INITIAL_DATA and message bus boundary; this allows the URI to focus on the proper codemod regardless if the webview has been initialized or not
you can try the following URL to test:
`vscode://intuita.intuita-vscode-extension/test?chd=oU68MgnhDvq08nBVNTQK8fouqGI`
The codemod hash digest are Base64URL-encoded on purpose so these links are possible.
> Provide the URI to select a specific codemod in public registry in the Intuita VSCode Extension

- intuita-webview/src/jobDiffView/App.tsx
- intuita-webview/src/jobDiffView/Components/Collapsable.tsx
- intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
- intuita-webview/src/jobDiffView/DiffViewer/index.tsx
After #377 (which led to changes in HTML structure of diff view), the function of showing the relevant file on focusing on folder in "Change Explorer" panel is broken. This PR fixes it.
> Fix showing relevant diff view on focusing folder

- intuita-webview/src/communityView/style.module.css
- intuita-webview/src/jobDiffView/DiffViewer/Container.css
- intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
Claap: https://app.claap.io/intuita/remove-outline-css-that-happens-remains-on-after-pressing-a-button-c-BT2DRbCjzO-nkdZwKck2GFa
> Remove outline CSS that happens/remains on/after pressing a button

- intuita-webview/src/codemodList/components/Container.css
- intuita-webview/src/codemodList/components/Container.tsx
- intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
- intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
- intuita-webview/src/shared/Popover/index.tsx
- in file diff view header, let's say "(created)" instead of "(copied)"
- Create a popover that appears when hovering over the new file name. The Popover should say "Copied from oldFileName"
> Change UI for Copy Job Kind in Diff View

- intuita-webview/src/codemodList/TreeView/TreeItem.tsx
- intuita-webview/src/codemodList/TreeView/style.module.css
- intuita-webview/src/codemodList/components/DirectorySelector.tsx
1. Execution path starts with repo name. e.g., `cal.com/` instead of `./`
2. Italicize repo name in execution path label in button. (in textfield, it's bit more complicated)
3. Even if user no longer hovers over the item, the edit path textfield will be visible.
4. Edit path textfield takes the entire real estate.
> Improvements to Edit Path item

- intuita-webview/pnpm-lock.yaml
- intuita-webview/src/codemodList/App.tsx
- intuita-webview/src/codemodList/TreeView/index.tsx
- intuita-webview/src/sourceControl/App.tsx
- src/components/webview/CodemodListProvider.ts
- src/components/webview/webviewEvents.ts
- src/persistedState/workspaceState.ts
Changes:
* save opened and focused codemod hash digests in the workspace state
* do not rely on the INITIAL_STATE window-level variable in the codemod view
This PR does not manage these hash digests, just provides the API to use them.
> INT-1064 save opened and focused codemod hash digests in the workspace state

- intuita-webview/src/codemodList/App.tsx
- intuita-webview/src/codemodList/TreeView/index.tsx
- src/components/webview/CodemodListProvider.ts
- src/components/webview/webviewEvents.ts
The codemod state (opened menu items and focus) are persisted using the workspace storage.
https://app.claap.io/intuita/codemod-state-persistence-c-BT2DRbCjzO-db-Lv9zx3PHV
> INT-1064 ensure that codemods state is persisted

- intuita-webview/src/codemodList/App.tsx
- intuita-webview/src/codemodList/components/Container.tsx
We want to save the state of the container (Public Codemods) expansion so it survives the destruction of the webview.
This PR is the first step to achieve that, by moving the expansion state to the root component.
In addition, I cleaned up the tech debt by inlining some components like the loading container and the header.
> INT-1121 manage the container state in the root App.tsx file

- src/components/webview/CodemodListProvider.ts
- src/components/webview/VirtualDocumentProvider.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
- src/utilities.ts
Changes:
* fetch files from index.json located on S3 to fetch codemod metadata
* add the `codemodMetadataHash` method to calculate the hash of the readme files
> INT-1144 use index.json from s3 to fetch codemod metadata

- src/components/downloadService.ts
- src/components/webview/VirtualDocumentProvider.ts
- src/extension.ts
https://app.claap.io/intuita/cached-codemod-metadata-c-BT2DRbCjzO-AtPIArf6gn04
If the codemod data have been already retrieved, it will be cached in the global storage.
We have a limitation stemming from the surviving virtual-document editor views - the VSCode Editor loads faster than the extension can claim the `codemod` scheme for the virtual document.
> INT-1144 cache the codemod data in the global storage

- intuita-webview/src/codemodList/components/DirectorySelector.tsx
Ensure that path always starts with repo name + slash. User can't override this restriction.
> Default filepath, / removed, enter does not work

- intuita-webview/src/errors/App.tsx
- src/components/engineService.ts
- src/components/messageBus.ts
- src/components/webview/CampaignManagerProvider.ts
- src/components/webview/CodemodListProvider.ts
- src/components/webview/ErrorWebviewProvider.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
- src/persistedState/workspaceState.ts
https://app.claap.io/intuita/error-panel-c-BT2DRbCjzO-KMBj209_uBAw
Changes:
1. the panel data is sourced from the workspace state at all times
2. the panel shows data during the panel recreation due to 1)
3. the panel is scrollable
4. the panel header is sticky
The discrepancy between the Campaign View (codemod runs) selection and the panel will be tackled in a subsequent PR.
> INT-1070 implement the Intuita Errors panel

- intuita-webview/src/codemodList/TreeView/TreeItem.tsx
- intuita-webview/src/codemodList/TreeView/index.tsx
- src/components/webview/CodemodListProvider.ts
- src/components/webview/webviewEvents.ts
> Preserve focus on discovery on single click and open doc on doublie click + popover to explain the double click

- src/components/webview/ErrorWebviewProvider.ts
If we show the panel without waiting for the changes to be input in the store, the following might happen:
1. the panel is shown (with no errors to show)
2. the store updates with the new errors
3. the message handler in the view is not connected yet, which means the new errors are not updated in the view
> INT-1190 show the error panel in the store subscriber

- intuita-webview/src/fileExplorer/Tree/index.tsx
> Fix wrong arrow-up behaviour when file and folder are siblings

- intuita-webview/src/intuitaTreeView.tsx
- src/selectors/selectExplorerTree.ts
Changes:
* ensure that the explorer tree is the object with minimal data (that's why we have the node data there, other structures were not necessary)
* use the custom tree view implementation
* ensure keyboards events are respected
> INT-1206 refactor selectExplorerTree and the IntuitaTreeView

- intuita-webview/src/communityView/App.tsx
- src/components/webview/CommunityProvider.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
Changes:
* use only the `INITIAL_STATE` in the Community tab
* remove event handling from the Community tab
* remove `webview.community.setView` and `webview.community.afterWebviewMounted` events
> INT-1206 simplify community provider

- src/data/slice.ts
- src/extension.ts
- src/persistedState/codecs.ts
Since the adoption of the tabs in the main view, we don't need to track the `visible` property of the tab, because their visibility is managed by the `activeTabId`.
Also, the `visible` property was essentially dead code.
> INT-1228 remove the visibility state from the (former) views, now tabs

- src/cases/types.ts
- src/components/webview/CampaignManagerProvider.ts
- src/components/webview/CodemodListProvider.ts
- src/components/webview/DiffWebviewPanel.ts
- src/components/webview/webviewEvents.ts
- src/data/slice.ts
- src/extension.ts
- src/persistedState/codecs.ts
- src/utilities.ts
Removes all the removable usages of ElementHash.
In general, the "elements" are going to be removed in the subsequent PR, where I will have refactored the Codemod Runs and use the new tree there.
> INT-1206 remove the usages of ElementHash

- intuita-webview/src/campaignManager/App.tsx
- intuita-webview/src/shared/types.ts
- src/components/webview/CampaignManagerProvider.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
Changes:
* open the diff panel after clicking (or focusing) on the codemod run
* remove unused structures in `src/components/webview/webviewEvents.ts`
* remove `intuita.openChangeExplorer` (the change explorer is part of the same tab as the codemod runs)
> INT-1206 restore opening of the diff panel after clicking on the codemod run

- intuita-webview/src/fileExplorer/explorerNodeRenderer.tsx
- intuita-webview/src/jobDiffView/hooks/useKey.ts
- intuita-webview/src/shared/TreeItem/index.tsx
- src/data/slice.ts
Changes:
* instead of using `useEffect`, use `useLayoutEffect`
* use `ref` instead of `getElementById`
* when launching `setSelectedCaseHash` action, clean up the selection of `focusedFileExplorerNodeId`
> INT-1206 improve the reactivity of the keyboard events

- intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
- intuita-webview/src/codemodList/CodemodNodeRenderer/Directory.tsx
- intuita-webview/src/codemodList/CodemodNodeRenderer/index.tsx
- intuita-webview/src/codemodList/components/DirectorySelector.tsx
-separate nodeRenderer component to 2 components: Codemod and Directory 
-removes a lot of conditions, improves readability, increase performance because resizing hook and logic is now only within Codemod component, and Directory is small and memoized
> split renderer

- intuita-webview/package.json
- intuita-webview/pnpm-lock.yaml
- intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
- intuita-webview/src/codemodList/CodemodNodeRenderer/index.tsx
- intuita-webview/src/codemodList/TreeView/index.tsx
- intuita-webview/src/jobDiffView/App.tsx
- intuita-webview/src/jobDiffView/index.css
- src/components/webview/CodemodDescriptionProvider.ts
- src/components/webview/CodemodListProvider.ts
- src/components/webview/IntuitaPanelProvider.ts
- src/components/webview/panelViewProps.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
- src/selectors/selectCodemodTree.ts
Change:
* move the codemod description view into the panel
* remove the `onDoubleClick` handler
* refactor `TextDocumentContentProvider` into `CodemodDescriptionProvider`
* we cannot show a codemod description and a job diff at the same time
Implemented over @hbjORbj changes
[Screencast from 24.06.2023 13:38:57.webm](https://github.com/intuita-inc/intuita-vscode-extension/assets/35925521/a588a975-b2d5-4f86-a8c7-2f2adffa745e)
> INT-1196 move the codemod description view into the panel

- intuita-webview/src/codemodList/CodemodNodeRenderer/Directory.tsx
- intuita-webview/src/codemodList/CodemodNodeRenderer/index.tsx
- intuita-webview/src/codemodList/components/DirectorySelector.tsx
Remove the dependency on `childCount` and enable the edit path on double click (the latter was requested by Alex)
> INT-1241 directory refactoring

- src/persistedState/explorerNodeCodec.ts
The new explorer codec, more suitable for the data persisted in the store and streamed down to the selectors and later to the components.
> INT-1241 the new explorer node codec

- intuita-webview/src/campaignManager/App.tsx
- intuita-webview/src/errors/App.tsx
- intuita-webview/src/fileExplorer/ActionsHeader/index.tsx
- intuita-webview/src/fileExplorer/App.tsx
- intuita-webview/src/fileExplorer/explorerNodeRenderer.tsx
- intuita-webview/src/intuitaTreeView.tsx
- intuita-webview/src/jobDiffView/DiffViewer/index.tsx
- src/cases/caseManager.ts
- src/cases/types.ts
- src/components/engineService.ts
- src/components/jobManager.ts
- src/components/messageBus.ts
- src/components/webview/ErrorWebviewProvider.ts
- src/components/webview/IntuitaPanelProvider.ts
- src/components/webview/MainProvider.ts
- src/components/webview/webviewEvents.ts
- src/data/slice.ts
- src/extension.ts
- src/persistedState/codecs.ts
- src/selectors/selectCodemodRunsTree.ts
- src/selectors/selectCodemodTree.ts
- src/selectors/selectExplorerTree.ts
https://linear.app/intuita/issue/INT-1241/change-the-change-explorers-state-to-allow-for-directory-selection
Changes:
* `selectedNodeHashDigest` -> `focusedNodeHashDigest` b/c the former means the checkbox selection, not the focus
* `childCount` -> `collapsible` (we don't need precise count)
* `CaseWithJobHashes` got removed, all usages replaced with `Case`
* add `MessageKind.mainWebviewViewVisibilityChange` message
* refactor selectors & actions to match the new structures in the store
> INT-1241 Change the change explorer's state to allow for directory selection

- intuita-webview/src/main/App.tsx
- intuita-webview/src/main/CodemodRuns.tsx
- intuita-webview/src/shared/SectionHeader/index.tsx
- src/components/webview/MainProvider.ts
- src/components/webview/webviewEvents.ts
- src/data/slice.ts
- src/selectors/selectMainWebviewViewProps.ts
Changes
* removed the `RESIZABLE_PANELS` constant and the way the CodemodRuns build the panels; now it's explicit
* introduced the `PanelGroupStorage` structure to support reading and writing of panel group's sizes
* collapse or expand panels when the store props change (including the changes stemming from user clicks and from the 3rd party library that ensures that one panel is always visible)
* add `collapseResultsPanel` and `collapseChangeExplorerPanel` actions AND webview responses
* remove the `CollapsibleWebviews` structure
[Screencast from 04.07.2023 16:53:47.webm](https://github.com/intuita-inc/intuita-vscode-extension/assets/35925521/fb0864bd-359d-457b-bc7a-f83626ad5702)
> INT-1304 refactor the CodemodRuns Tab to control collapsing/expanding of panels

- src/selectors/selectExplorerTree.ts
-- adds compact tree view, same as in vscode file explorer
> collapse nested folders

- package.json
- src/components/bootstrapExecutablesService.ts
- src/components/buildArguments.ts
- src/components/engineService.ts
- src/components/messageBus.ts
- src/extension.ts
- src/telemetry/vscodeTelemetry.ts
Changes:
* added the `intuita.executeAsPiranhaRule` command,
* added the `codemodEngineNodeExecutableUri` (now hardcoded) URI,
* removed unused and doubled property from the `Execution` type,
* take the `codemodName` from the state or from the command
> INT-1313 add ability to run Piranha rules

- package.json
- pnpm-lock.yaml
- src/codemods/types.ts
- src/components/bootstrapExecutablesService.ts
- src/components/buildArguments.ts
- src/components/engineService.ts
- src/components/messageBus.ts
- src/components/webview/CodemodDescriptionProvider.ts
- src/data/index.ts
- src/data/slice.ts
- src/extension.ts
Changes:
* since now, the new version of the Codemod Engine Node will fetch the codemods into the `os.homedir()/.intuita` directory
* the arguments build by `buildArguments` function are more human readable
* the messages coming from the CEN are more readable as well, there's a new codec / schema for that
* there is no `executeRepomod` subcommand, the CEN doesn't differentiate
* the hardcoded codemod hashes are no longer in the codebase
* the `CodemodDescriptionProvider` only calculates where the descriptions are, without fetching codemods
* the action for previously upserting codemods now sets them (removing all previous codemods in the list)
> INT-1421 use the CLI (CEN) for fetching and running codemods

- intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
- src/components/webview/MainProvider.ts
- src/components/webview/webviewEvents.ts
- src/extension.ts
- src/telemetry/vscodeTelemetry.ts
1. Display private codemod name, not hash in "Results" list
2. Private codemod name should be used for report issue title
> INT-1791 INT-1732 handle name for private codemod

- src/components/webview/SourceControlPanelProvider.ts
- src/extension.ts
- With a modal, notify the user that a linked Github account is required and hence we are routing the user to Github sign-in to proceed with creating an issue
> INT-1752 Integration 2

- src/components/downloadService.ts
- src/components/engineService.ts
- src/components/userService.ts
- src/components/webview/IntuitaPanelProvider.ts
- src/components/webview/SourceControlPanelProvider.ts
- src/extension.ts
- src/github/types.ts
- Use global extension storage to save user's clerk token
- if user's clerk token doesn't exist in global storage, redirect user to codemod studio with a search param `userTokenRequestFromVSCode`
> INT-1752 integration for report issue feature

- intuita-webview/src/CreateIssue/index.tsx
- src/components/webview/MainProvider.ts
claap: https://app.claap.io/intuita/two-improvements-to-the-ux-ui-of-reporting-issue-feature-c-BT2DRbCjzO-pwv6SM74ESqr
> INT-1831 two improvements to the UX/UI of reporting issue feature

- package.json
- src/extension.ts
- If access token stored in vscode extension storage is invalid, automatically sign out user and show notif saying "'You are signed out because your session has expired.'". 
- icon on the sidebar toolbar must change to reflect the account sign-in status
> INT-1902 Handle account session expiry

- intuita-webview/src/codemodList/CodemodArguments/FormField/index.tsx
> INT-2094 Can't understand that `*` means a required codemod arg

- intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
- intuita-webview/src/codemodList/CodemodNodeRenderer/style.module.css
- intuita-webview/src/codemodList/TreeView/style.module.css
> INT-2372 Fix the selection color for light theme
