src/components/acceptJob.ts
src/components/diagnosticManager.ts
src/components/fileService.ts
src/components/inferredCodeRepairService.ts
src/components/internalService.ts
src/components/jobManager.ts
src/components/messageBus.ts
src/components/vscodeService.ts
src/destructIntuitaFileSystemUri.ts
src/extension.ts

https://linear.app/intuita/issue/INT-195/refactor-the-acceptjob-functionality

INT-195 refactor the accept-job functionality

---

package.json
src/components/diagnosticManager.ts
src/components/jobManager.ts
src/components/vscodeService.ts
src/configuration.ts
src/extension.ts

https://linear.app/intuita/issue/INT-202/run-code-repair-on-command-or-on-save

INT-202 Run code-repair on command or on save

---

src/components/jobManager.ts
src/features/repairCode/buildReplacement.ts
src/features/repairCode/buildRuleBasedRepairCodeJobs.ts
src/test/buildReplacement.test.ts

https://linear.app/intuita/issue/INT-197/rule-based-code-repair-remove-quotes-instead-of-wrapping

INT-197 Rule-based Code Repair: Remove quotes instead of wrapping

---

.gitignore
src/components/acceptJob.ts
src/components/diagnosticManager.ts
src/components/inferredCodeRepairService.ts
src/components/intuitaCodeActionProvider.ts
src/components/intuitaTreeDataProvider.ts
src/components/jobManager.ts
src/components/messageBus.ts
src/components/ruleBasedCodeRepairService.ts
src/extension.ts

https://linear.app/intuita/issue/INT-206/show-the-first-job-for-the-file-from-which-code-repair-was-invoked

INT-206 Show the first job for the file from which code-repair was invoked

---

package.json
src/components/inferenceService.ts
src/components/inferredCodeRepairService.ts
yarn.lock

https://linear.app/intuita/issue/INT-226/have-the-extension-call-the-intuita-joern-proxy

INT-226 have the extension call the joern proxy

---

package.json
src/components/intuitaTreeDataProvider.ts
src/types/vscode.d.ts
yarn.lock

https://linear.app/intuita/issue/INT-229/extend-the-typescript-definitions-to-include-the-new-vscode-features

INT-229 Extend the TypeScript definitions to include the new VSCode features

---

src/classifier/classify.ts
src/classifier/types.ts
src/features/moveTopLevelNode/2_factBuilders/typeScriptFactBuilder.ts
src/test/classifier/classifier.test.ts
src/test/classifier/code.txt
src/test/classifier/diagnostics.txt
src/types/vscode.d.ts

https://linear.app/intuita/issue/INT-230/build-the-rudimentary-classifier

Build the rudimentary classifier

---

src/components/diagnosticManager.ts
src/diagnostics/buildDiagnosticHash.ts
src/diagnostics/types.ts
src/test/diagnostics/buildDiagnosticHash.test.ts
src/uris/buildUriHash.ts
src/uris/types.ts
src/utilities.ts
src/vscode/types.ts

https://linear.app/intuita/issue/INT-231/rewrite-the-diagnostic-hash

INT-231 Rewrite the Diagnostic Hash

---

src/classifier/similarity.ts
src/test/classifier/getWords.test.ts

https://linear.app/intuita/issue/INT-232/build-the-similarity-calculator

INT-232 build the similarity calculator

---

src/components/jobManager.ts
src/elements/buildFileElement.ts

https://linear.app/intuita/issue/INT-243/remove-the-vfs-original-file-copy-after-a-single-job-has-been-accepted

INT-243 Remove the VFS original file copy after a single job has been accepted

---

src/components/ruleBasedCodeRepairService.ts

https://linear.app/intuita/issue/INT-246/do-not-create-cases-for-diagnostics-without-rule-based-fixes

INT-246 do not create cases for diagnostics without rule-based fixes

---

package.json
src/cases/caseManager.ts
src/components/intuitaTreeDataProvider.ts
src/components/jobManager.ts
src/components/messageBus.ts
src/configuration.ts
src/elements/buildDiagnosticElement.ts
src/elements/buildFileElement.ts
src/elements/buildJobElement.ts
src/elements/getFirstJobElement.ts
src/elements/types.ts
src/extension.ts

https://linear.app/intuita/issue/INT-248/file-grouping-switch-in-the-intuita-view

INT-248 File grouping switch in the Intuita View

---

src/cases/caseManager.ts
src/components/diagnosticManager.ts
src/components/inferredCodeRepairService.ts
src/components/jobManager.ts
src/components/messageBus.ts
src/components/moveTopLevelNodeBlocksService.ts
src/components/ruleBasedCodeRepairService.ts
src/features/moveTopLevelNode/job.ts
src/features/repairCode/job.ts
src/jobs/types.ts

https://linear.app/intuita/issue/INT-270/break-the-symmetry-between-diagnostics-and-jobs

INT-270 break the symmetry between diagnostics and jobs

---

src/cases/buildCaseHash.ts
src/cases/caseManager.ts
src/cases/types.ts
src/classifier/buildCases.ts
src/classifier/classify.ts
src/classifier/types.ts
src/components/inferredCodeRepairService.ts
src/components/moveTopLevelNodeBlocksService.ts
src/components/ruleBasedCodeRepairService.ts
src/elements/buildCaseElement.ts
src/features/repairCode/buildReplacementEnvelope.ts
src/features/repairCode/buildTs2322NextJsImageLayoutReplacementEnvelope.ts
src/features/repairCode/buildTs2345PrimitivesReplacementEnvelope.ts
src/features/repairCode/buildTs2741NextJsImageAltReplacementEnvelope.ts
src/features/repairCode/buildTs2769ObjectAssignReplacementEnvelope.ts
test/classifier/classifier.test.ts

https://linear.app/intuita/issue/INT-271/refactor-the-case-management-so-it-supports-distinct-case-features

INT-271 refactor the case management so it supports distinct case features

---

package.json
src/components/fileSystemUtilities.ts
src/components/inferredCodeRepairService.ts
src/components/polyglotPiranhaRepairCodeService.ts
src/extension.ts
tsconfig.json

https://linear.app/intuita/issue/INT-268/pull-polyglot-piranha-builds-from-s3

INT-268 pull Polyglot Piranha executable and rules and execute them

---

src/components/polyglotPiranhaRepairCodeService.ts

https://linear.app/intuita/issue/INT-257/integrate-the-nextjs-link-codemod-using-piranha

INT-257 Integrate the Next.js link codemod using Piranha (basic version)

---

src/components/polyglotPiranhaRepairCodeService.ts

https://linear.app/intuita/issue/INT-256/integrate-the-nextjs-next-image-to-legacy-image-codemod-using-piranha

INT-256 Integrate the Next.js next-image-to-legacy-image codemod using Piranha

---

src/cases/buildCaseHash.ts
src/cases/types.ts
src/classifier/buildCases.ts
src/components/polyglotPiranhaRepairCodeService.ts
src/elements/buildCaseElement.ts

https://linear.app/intuita/issue/INT-275/introduce-subkinds-into-repair-code-jobs-by-piranha-polyglot

INT-275 Introduce subkinds into repair-code jobs by Piranha Polyglot

---

src/components/polyglotPiranhaRepairCodeService.ts
src/extension.ts

https://linear.app/intuita/issue/INT-281/inform-the-user-about-unsupported-arch-platform

INT-281 Inform the user about unsupported arch + platform

---

package.json
src/cases/buildCaseHash.ts
src/cases/types.ts
src/components/downloadService.ts
src/components/intuitaCodeActionProvider.ts
src/components/intuitaFileSystem.ts
src/components/jobManager.ts
src/components/noraNodeEngineService.ts
src/components/polyglotPiranhaRepairCodeService.ts
src/elements/buildCaseElement.ts
src/elements/buildJobElement.ts
src/elements/types.ts
src/extension.ts
src/features/rewriteFile/job.ts
src/jobs/types.ts

https://linear.app/intuita/issue/INT-285/support-the-nora-node-engine-within-the-intuita-vscode-extension

INT-285 Support for nora node engine

---

package.json
src/components/engineService.ts
src/components/noraNodeEngineService.ts
src/components/noraRustEngineService.ts

https://linear.app/intuita/issue/INT-302/inform-the-user-that-executables-are-being-fetched

Inform the user that executables are being fetched

---

package.json
src/components/bootstrapExecutablesService.ts
src/components/engineService.ts
src/components/statusBarItemManager.ts
src/extension.ts

https://linear.app/intuita/issue/INT-308/show-codemod-progress-in-the-extension

INT-308 Show codemod progress in the extension

---

package.json
src/cases/caseManager.ts
src/cases/types.ts
src/components/intuitaTreeDataProvider.ts
src/components/jobManager.ts
src/components/messageBus.ts
src/extension.ts
src/leftRightHashes/leftRightHashSetManager.ts
src/persistedState/codecs.ts
src/persistedState/getPersistedState.ts
src/persistedState/mappers.ts
src/persistedState/persistedStateService.ts
src/utilities.ts

https://linear.app/intuita/issue/INT-309/persist-the-intuita-case-and-job-information-in-intuita-directory

INT-309 Persist the Intuita case and job information in .intuita directory

---

package.json

https://linear.app/intuita/issue/INT-133/acceptreject-does-not-work-from-f1-command

INT-133 do not show UI-bound commands in the palette

---

package.json
src/components/engineService.ts
src/configuration.ts
src/extension.ts

https://linear.app/intuita/issue/INT-312/allow-the-file-limit-to-be-set-in-the-settings

INT-312 allow the file limit to be set in the settings

---

src/extension.ts
src/persistedState/getPersistedState.ts
src/persistedState/persistedStateService.ts

https://linear.app/intuita/issue/INT-315/persist-state-in-the-workspace-storage-instead-of-workspace-files

INT-315 persist state in the workspace storage instead of workspace files

---

package.json
src/components/bootstrapExecutablesService.ts
src/components/downloadService.ts
src/components/engineService.ts
src/components/informationMessageService.ts
src/components/messageBus.ts
src/dependencies/dependencyService.ts
src/extension.ts
yarn.lock

https://linear.app/intuita/issue/INT-296/ux-trigger-command-from-packagejson

INT-296 UX-trigger command from package.json

---

src/components/bootstrapExecutablesService.ts
src/components/engineService.ts
src/components/informationMessageService.ts
src/components/messageBus.ts
src/extension.ts

https://linear.app/intuita/issue/INT-334/bootstrap-engines-upon-extension-activation

INT-134 Bootstrap Engines upon Extension Activation

---

cspell.json
package.json
src/components/bootstrapExecutablesService.ts
src/components/messageBus.ts
src/extension.ts

https://linear.app/intuita/issue/INT-344/integrate-v3v6-react-router-codemods-into-the-vscode-extension

INT-344 Integrate v3/v6 React Router codemods into the VSCode Extension

---

README.md
package.json
src/components/bootstrapExecutablesService.ts
src/components/engineService.ts
src/components/messageBus.ts
src/extension.ts

https://linear.app/intuita/issue/INT-347/add-js-to-the-activation-event-for-the-extension
Changes:
* activate the extension over JS/JSX/TS/TSX files
* run the codemod sets over JS/JSX/TS/TSX files

INT-347 use the extension over JS/JSX/TS/TSX files

---

package.json
src/components/informationMessageService.ts
src/components/messageBus.ts
src/extension.ts

https://linear.app/intuita/issue/INT-364/support-redwoodjscore-codemod-execution-from-packagejson-and-a-command

INT-364 support @redwoodjs/core codemod execution from package.json and a command

---

package.json
src/components/engineService.ts
src/components/fileService.ts
src/components/jobManager.ts
src/components/messageBus.ts
src/elements/buildJobElement.ts
src/jobs/types.ts
src/persistedState/codecs.ts

https://linear.app/intuita/issue/INT-396/support-copying-files-in-the-intuita-vscode-extension

INT-396 Support copying files in the Intuita VSCode Extension

---

src/components/jobManager.ts
src/extension.ts
src/persistedState/codecs.ts
src/persistedState/persistedStateService.ts

Fixes https://linear.app/intuita/issue/INT-732/[ide-ext]-re-executing-recipe-after-dismissing-casejob-in-the-previous#comment-135c13bd
- Tested
- `yarn package` succeeds

[IDE ext] Re-executing recipe after dismissing case/job in the previous execution ignores the case/job

---

intuita-webview/src/App.tsx
intuita-webview/src/CreatePRView/index.tsx
intuita-webview/src/CreatePRView/style.module.css
package.json
src/components/webview/IntuitaPanel.ts
src/components/webview/sourceControl.ts
src/extension.ts

Added  UI for creating Pull Request from extension

Feature/int 734 add create pr UI to the webview

---

src/components/webview/repository.ts
src/extension.ts

Changes
* allows instantiate the repository service
* allows initialize the `__repo` member

Rewrite the repository service

---

intuita-webview/src/App.tsx
package.json
src/components/messageBus.ts
src/components/webview/IntuitaPanel.ts
src/components/webview/repository.ts
src/components/webview/sourceControl.ts
src/configuration.ts
src/extension.ts

Changes:
* remove the repositoryPath from the extension settings
* take the repository path from git settings and move it to the webviews if the path changes

Remove the repositoryPath from the extension settings

---

src/extension.ts

https://linear.app/intuita/issue/INT-756/[ide-ext]-selecting-applydiscard-in-intuita-tab-leads-to-explorer-tab
https://user-images.githubusercontent.com/32841130/230590076-666b6728-5503-44f0-bd3d-3033f3b4a9ce.mov
https://user-images.githubusercontent.com/32841130/230590004-73056523-8920-446b-a953-6bec7e91796a.mov

[IDE ext.] Selecting Apply/Discard in Intuita tab leads to Explorer Tab

---

intuita-webview/src/assets/folder.svg
intuita-webview/src/main/Tree/index.tsx
intuita-webview/src/main/TreeView/index.tsx
package.json
src/components/intuitaTreeDataProvider.ts
src/components/messageBus.ts
src/components/webview/MainWebviewProvider.ts
src/elements/buildCaseElement.ts
src/elements/buildFileElement.ts
src/elements/buildJobElement.ts
src/elements/types.ts
src/extension.ts

https://linear.app/intuita/issue/INT-771/allow-user-to-optionally-break-down-jobs-in-folder-hierarchy#comment-fb1fb47c
https://user-images.githubusercontent.com/32841130/231420311-4e73461f-7df2-4f3b-bd92-cbefa48a5aff.mov

Allow user to optionally break down jobs in folder hierarchy

---

src/components/intuitaTreeDataProvider.ts
src/components/webview/MainWebviewProvider.ts
src/elements/types.ts
src/utilities.ts

Improve Tree View Root Label from 'Recipe'

---

src/components/noraCompareServiceEngine.ts

Fix `codemodName` / `codemodSetName` fields for case

---

intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
intuita-webview/src/jobDiffView/DiffViewer/index.tsx

(1) Change the “in-line / side-by-side” dropdown in Header of diff view to something one-click. I changed it to Radios. 
(2) Remove the “in-line / side-by-side” dropdown per file.
Linear: https://linear.app/intuita/issue/INT-840/simplify-diff-view-ui

Simplify Diff view UI

---

intuita-webview/src/main/TreeItem/index.tsx
intuita-webview/src/main/TreeItem/style.module.css
intuita-webview/src/main/TreeView/index.tsx
intuita-webview/src/shared/Tree/index.tsx
intuita-webview/src/sourceControl/CommitView/ChangesList.tsx
intuita-webview/src/utilities.ts
package.json
src/components/webview/MainWebviewProvider.ts
src/extension.ts

https://linear.app/intuita/issue/INT-820/smart-defaults-for-branching-out-and-creating-pr
https://user-images.githubusercontent.com/32841130/233644720-a9316a62-384f-4903-8aad-90bb82a9bdcb.mov

New UI for Folder breakdown + Commit workflow for Folder breakdown

---

package.json
src/extension.ts

https://linear.app/intuita/issue/INT-846/refactoring-of-the-intuita-view-container

INT-846 refactored the intuita view container

---

intuita-webview/src/main/App.tsx
intuita-webview/src/main/SearchBar/index.tsx
intuita-webview/src/main/SearchBar/style.module.css
intuita-webview/src/main/TreeItem/index.tsx
intuita-webview/src/main/TreeItem/style.module.css
intuita-webview/src/main/TreeView/index.tsx
intuita-webview/src/shared/Tree/index.tsx
intuita-webview/src/sourceControl/CommitView/ChangesList.tsx
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts

https://user-images.githubusercontent.com/32841130/234349799-0b5cc8a9-e9dd-412c-9c1d-da2bab24f48f.mov

Add search bar functionality to File Explorer Panel

---

intuita-webview/src/campaignManager/ListView/index.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
src/components/webview/CampaignManagerProvider.ts
src/components/webview/FileExplorerProvider.ts

1st part of https://linear.app/intuita/issue/INT-872/show-all-files-in-the-diff-view-and-use-the-file-explorer-view-to-move
https://user-images.githubusercontent.com/32841130/234664530-02b51374-dda8-4e6a-9fbc-1b9d31bfd0b4.mov

Show all files in the diff view (on running codemod and on pressing codemod element in Branch manager panel)

---

src/components/webview/CampaignManagerProvider.ts

Remove discard button from case element

---

intuita-webview/package.json
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/hooks/useKey.ts
intuita-webview/src/shared/Tree/index.tsx
intuita-webview/src/shared/TreeItem/style.module.css
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts

https://user-images.githubusercontent.com/32841130/234868426-be839c1e-3a71-41a9-b6a3-16dfd1510fa4.mov

Select different files and Expand / Collapse folder using keyboard shortcuts in Change Explorer Panel

---

src/components/webview/SourceControlWebviewPanel.ts

This clears Code change Projects and Change explorer panels on committing or committing & PR or creating issue

Clear state on Create PR / Commit / Create Issue

---

intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
src/components/webview/DiffWebviewPanel.ts
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts

2nd part of https://linear.app/intuita/issue/INT-872/show-all-files-in-the-diff-view-and-use-the-file-explorer-view-to-move
https://app.claap.io/intuita/scroll-to-specific-file-on-select-c-BT2DRbCjzO-b01VP7wIPW5R

Use the file explorer view to move between different files

---

intuita-webview/src/campaignManager/App.tsx
intuita-webview/src/campaignManager/ListView/index.tsx
intuita-webview/src/codemodList/TreeView/index.tsx
intuita-webview/src/fileExplorer/App.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
src/components/webview/CampaignManagerProvider.ts
src/components/webview/CodemodListProvider.ts
src/components/webview/DiffWebviewPanel.ts
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts
src/extension.ts

Support Running Multiple Codemods and File Explorer changes depending on which case in selected

---

intuita-webview/src/codemodList/App.tsx

Hide "Build it yourself" view

---

intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
src/components/webview/DiffWebviewPanel.ts

Make the title of Diff view more descriptive

---

intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
src/components/webview/CampaignManagerProvider.ts

Rename Save to File System to Apply all & Remove Commit/Discard buttons from case element

---

intuita-webview/src/campaignManager/ListView/index.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
intuita-webview/src/jobDiffView/DiffViewer/index.tsx
intuita-webview/src/shared/TreeItem/index.tsx
src/cases/caseManager.ts
src/components/sourceControl/codecs.ts
src/components/webview/CampaignManagerProvider.ts
src/components/webview/DiffWebviewPanel.ts
src/components/webview/webviewEvents.ts
src/extension.ts

https://app.claap.io/intuita/applied-case-element-must-stay-in-code-changes-project-with-less-opacity-c-BT2DRbCjzO-BA7lhUBDHGxU

Applied case element must stay in Code Changes Project with less opacity

---

intuita-webview/src/sourceControl/CommitView/index.tsx

hide pr button

---

intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
src/components/webview/DiffWebviewPanel.ts

Claap: https://app.claap.io/intuita/write-only-the-file-name-in-the-job-header-in-the-diff-view-c-BT2DRbCjzO-Hz_yJxWx9Qhk

Write only the file name in the job header in the diff view

---

intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
intuita-webview/src/shared/Collapsable/Collapsable.tsx
intuita-webview/src/shared/Popover/index.tsx

Linear: https://linear.app/intuita/issue/INT-955/add-popovers-for-descriptions-in-diff-view
Claap: https://app.claap.io/intuita/popovers-in-diff-view-c-BT2DRbCjzO-VRbjI6ud3Fef

Add Popovers for descriptions in Diff View

---

src/extension.ts

Name of the tab should be the same as in the Code Change Projects

---

intuita-webview/src/campaignManager/ListView/index.tsx
src/components/webview/CampaignManagerProvider.ts

Linear: https://linear.app/intuita/issue/INT-949/diff-view-flow-still-concepting

Do not put any buttons into the Code Change Projects view menu items (no Dismiss button)

---

intuita-webview/src/codemodList/components/Container.css
intuita-webview/src/codemodList/components/Container.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
intuita-webview/src/jobDiffView/DiffViewer/index.tsx
intuita-webview/src/shared/Collapsable/Collapsable.tsx
intuita-webview/src/shared/TreeItem/index.tsx
src/components/webview/DiffWebviewPanel.ts
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts

1. Collapse/Expand on pressing the Chevron only, not the item
2. Press on the folder element leads to the first file inside the folder

Improvements in File Explorer Panel

---

intuita-webview/src/campaignManager/App.tsx
intuita-webview/src/campaignManager/ListView/index.tsx
src/cases/caseManager.ts
src/components/webview/CampaignManagerProvider.ts
src/components/webview/webviewEvents.ts
src/extension.ts

Running codemod must have that codemod selected/focused in Code Change Projects automatically

---

intuita-webview/src/codemodList/App.tsx
src/components/webview/CodemodListProvider.ts
src/components/webview/webviewEvents.ts

Since we are no showing the recommended codemods right now, we could simplify the codemods app significantly.

INT-919 simplify the codemods app

---

intuita-webview/src/jobDiffView/DiffViewer/Container.css
intuita-webview/src/jobDiffView/DiffViewer/Container.tsx

Add (moved), (created), (deleted), (moved & rewritten), (copied) job kinds to the diff view header

---

intuita-webview/src/jobDiffView/App.tsx
src/components/webview/CampaignManagerProvider.ts
src/components/webview/DiffWebviewPanel.ts
src/extension.ts

- updates diff view as new jobs are pushed to the case

update diff view as new jobs are pushed to the case

---

intuita-webview/src/fileExplorer/SearchBar/index.tsx
intuita-webview/src/fileExplorer/SearchBar/style.module.css
intuita-webview/src/jobDiffView/hooks/useKey.ts

Fix Search bar in Change Explorer panel not working

---

intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/style.module.css
intuita-webview/src/jobDiffView/DiffViewer/index.tsx
src/components/jobManager.ts
src/components/webview/DiffWebviewPanel.ts
src/components/webview/webviewEvents.ts

- adds checkbox that allows to select/deselect all https://app.claap.io/intuita/c-BT2DRbCjzO-az1s5TXG3qKL

add checkbox

---

intuita-webview/src/campaignManager/ListView/index.tsx
intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/Components/LoadingProgress/index.tsx
intuita-webview/src/jobDiffView/Components/LoadingProgress/style.module.css
src/components/engineService.ts
src/components/webview/DiffWebviewPanel.ts
src/components/webview/webviewEvents.ts
src/extension.ts

do not show flickering jobs in the diff view

---

intuita-webview/src/shared/Popover/index.tsx

Claap: https://app.claap.io/intuita/popover-lingers-longer-that-it-should-c-BT2DRbCjzO-LnfXQiCHRx9v
Linear: https://linear.app/intuita/issue/INT-997/popover-lingers-longer-that-it-should

Popover lingers longer that it should

---

intuita-webview/src/fileExplorer/App.tsx
package.json
src/extension.ts

Rename "Code Change Projects" to "Recent Codemod Runs"

---

intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx

Fix Select all / Unselect all checkbox logic

---

intuita-webview/src/fileExplorer/App.tsx
package.json
src/extension.ts

Rename "Recent Codemod Runs" to "Codemod Runs"

---

intuita-webview/src/codemodList/App.tsx
src/components/webview/CodemodListProvider.ts
src/extension.ts
src/packageJsonAnalyzer/codemodService.ts

Fix the spinning wheel for loading public codemods when no workspace is open

---

cspell.json
intuita-webview/craco.config.ts
intuita-webview/package.json
intuita-webview/pnpm-lock.yaml
intuita-webview/public/index.html
intuita-webview/src/jobDiffView/DiffViewer/Diff.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
intuita-webview/src/jobDiffView/DiffViewer/index.tsx
intuita-webview/src/shared/Snippet/calculateDiff.tsx

- returns craco.config for local development
- builds webviews in production mode
- memoize MonacoEditor callbacks and component

diff view performance part 1

---

intuita-webview/src/codemodList/TreeView/index.tsx
intuita-webview/src/codemodList/TreeView/style.module.css
intuita-webview/src/codemodList/useProgressBar.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/HooksCTA/index.tsx
intuita-webview/src/shared/util.css

Codemod Discovery Panel UI improvements

---

intuita-webview/src/codemodList/TreeView/style.module.css
intuita-webview/src/fileExplorer/App.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/DiffViewer/Container.css
intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.css
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/index.tsx
intuita-webview/src/jobDiffView/DiffViewer/Header/style.module.css
intuita-webview/src/jobDiffView/DiffViewer/index.tsx
intuita-webview/src/shared/Tree/index.tsx
intuita-webview/src/shared/TreeItem/index.tsx
intuita-webview/src/shared/util.css
src/components/webview/DiffWebviewPanel.ts
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts
src/extension.ts

Display 1 diff at a time + Keyboard Accessibility Improvements

---

intuita-webview/src/codemodList/TreeView/Tree.tsx
intuita-webview/src/codemodList/TreeView/index.tsx
src/components/webview/CodemodListProvider.ts
src/components/webview/webviewEvents.ts
src/errors/types.ts

* use the Synthetic Error for errors that need to go thru the app/webview barrier
* These monad is for Eithers that can contains error and the correct value at the same time (this is basically a tri-state)

INT-1064 introduce a SyntheticError and These monad

---

src/components/engineService.ts
src/components/messageBus.ts
src/components/webview/CampaignManagerProvider.ts

- opens diff view when codemod is executed
- does not depend on codemod runs panel

fix diff view open

---

intuita-webview/src/codemodList/App.tsx
intuita-webview/src/codemodList/components/Container.tsx
src/components/webview/CodemodListProvider.ts
src/components/webview/webviewEvents.ts
src/persistedState/workspaceState.ts

https://app.claap.io/intuita/persist-the-public-codemods-expansion-state-c-BT2DRbCjzO-GpuXMf_-cDbL

INT-1121 persist the public codemods expansion into workspace state

---

intuita-webview/src/codemodList/components/Container.tsx
intuita-webview/src/shared/Collapsable/Collapsable.tsx
src/components/webview/CodemodListProvider.ts

https://app.claap.io/intuita/show-codemod-link-even-if-the-public-codemods-are-collapsed-c-BT2DRbCjzO-cDeieCnA0NdX

INT-1121 show codemod link even if the public codemods are collapsed

---

intuita-webview/src/codemodList/TreeView/index.tsx
intuita-webview/src/codemodList/useProgressBar.tsx
intuita-webview/src/shared/Popover/index.tsx

- Increase enter delay and reduce leave delay
- Replace native tooltip of dry-run button and stop button with our custom tooltip

Improvements to our custom Tooltip

---

intuita-webview/src/campaignManager/App.tsx
intuita-webview/src/campaignManager/ListView/index.tsx
src/extension.ts

closes https://linear.app/intuita/issue/INT-1138/diff-view-does-not-open

fix job diff opening

---

intuita-webview/src/jobDiffView/DiffViewer/index.tsx

Currently, we always reset the state of diff view to the default value when rendering it. This is a bug originating from this. This PR makes it to store the diff view state in an object properly with job hash as a key.

Viewed toggle getting unset when going back and forth between file diffs

---

src/components/engineService.ts
src/components/messageBus.ts
src/extension.ts

https://app.claap.io/intuita/single-file-exec-c-BT2DRbCjzO-i3QkyWv0gAWo

INT-1156 allow the CNE to execute against a single file

---

intuita-webview/src/codemodList/components/style.module.css

Make it explicit that Edit path button is clickable

---

intuita-webview/src/fileExplorer/TreeView/index.tsx

-fixes incorrect search behaviour 
https://app.claap.io/c-BT2DRbCjzO-ZnMKhzBEt2xj?ccl=1

fix search

---

intuita-webview/src/codemodList/TreeView/TreeItem.tsx
intuita-webview/src/codemodList/TreeView/index.tsx

Keyboard improvements in Codemod Discovery

---

intuita-webview/src/codemodList/App.tsx
intuita-webview/src/codemodList/TreeView/Tree.tsx
intuita-webview/src/codemodList/TreeView/index.tsx
src/components/webview/CodemodListProvider.ts
src/components/webview/webviewEvents.ts

when a folder is collapsed and you hit down arrow the selection wont be in the view and instead it seems that i goes into the children of that folder instead.

Further keyboard a11y improvements in discovery

---

src/components/webview/ErrorWebviewProvider.ts

https://app.claap.io/intuita/focus-error-view-c-BT2DRbCjzO-1xz_3YC164Do

INT-1070 focus on the error panel if there are execution errors

---

cspell.json
intuita-webview/src/main/App.tsx
src/components/webview/FileExplorerProvider.ts
src/components/webview/MainProvider.ts
src/components/webview/webviewEvents.ts
src/data/slice.ts
src/extension.ts

Control collapse/expand of the left panels & Expand codemod runs / change explorer on dry-run

---

intuita-webview/src/fileExplorer/TreeView/index.tsx

[Change Explorer] Debounce rendering diff view based on tree item focus

---

intuita-webview/src/codemodList/TreeView/Tree.tsx
intuita-webview/src/codemodList/TreeView/TreeItem.tsx
intuita-webview/src/codemodList/TreeView/index.tsx
intuita-webview/src/fileExplorer/Tree/index.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/hooks/useKey.ts

Change explorer & Codemod discovery must subscribe to keyboard events in their own tree views

---

intuita-webview/src/main/App.tsx
intuita-webview/src/shared/Panel.tsx

Fixes https://linear.app/intuita/issue/INT-1192/cursers-shape-hangs-when-a-section-in-the-left-panel-is-moved

fix resize cursor

---

intuita-webview/src/fileExplorer/App.tsx
intuita-webview/src/fileExplorer/style.module.css
intuita-webview/src/main/App.tsx

Fixes https://linear.app/intuita/issue/INT-1194/action-buttons-get-hidden-and-unaccessible-when-user-navigates-down-in

fix hidden buttons

---

src/jobs/types.ts

Fixes https://linear.app/intuita/issue/INT-1215/the-jobs-dont-get-applied-after-clicking-apply-selected

fix files not applied

---

intuita-webview/src/campaignManager/index.tsx
intuita-webview/src/codemodList/App.tsx
intuita-webview/src/codemodList/index.tsx
intuita-webview/src/communityView/index.tsx
intuita-webview/src/fileExplorer/App.tsx
intuita-webview/src/fileExplorer/index.tsx
intuita-webview/src/shared/SearchBar/index.tsx

The idea is that the search phrase comes from the Redux store and thus will be no longer a part of local state in components.

INT-1206 refactor the search bar

---

intuita-webview/src/fileExplorer/ActionsHeader/index.tsx
intuita-webview/src/fileExplorer/App.tsx
src/components/jobManager.ts
src/components/webview/webviewEvents.ts

Ensure that the actions header does not depend on structures specific to the previous tree implementation.

INT-1206 refactor actions header

---

intuita-webview/src/fileExplorer/explorerNodeRenderer.tsx

This servers as a concrete implementation of a node renderer.
In the future, we will refactor the TreeItem as well.

INT-1206 implement the explorer node renderer

---

intuita-webview/src/fileExplorer/App.tsx
intuita-webview/src/fileExplorer/TreeView/index.tsx
intuita-webview/src/jobDiffView/hooks/useKey.ts
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts
src/data/slice.ts
src/extension.ts
src/selectors/selectExplorerTree.ts

https://app.claap.io/intuita/treeview-c-BT2DRbCjzO-cm65es4sHXIc

apply the intuita tree view to the change explorer

---

intuita-webview/src/codemodList/codemodNodeRenderer.tsx
src/components/webview/CodemodListProvider.ts
src/selectors/selectCodemodTree.ts

add codemod node renderer

---

src/components/webview/CodemodListProvider.ts
src/data/slice.ts
src/persistedState/codecs.ts
src/selectors/selectCodemodTree.ts

-replaces expanded nodes with collapsed
-fixes for treeSelector

fix codemod tree selector

---

intuita-webview/src/fileExplorer/App.tsx
intuita-webview/src/jobDiffView/App.tsx
src/components/messageBus.ts
src/components/webview/DiffWebviewPanel.ts
src/components/webview/FileExplorerProvider.ts
src/components/webview/webviewEvents.ts
src/selectors/selectExplorerTree.ts

https://app.claap.io/intuita/diffviewinteractswithchangeexplorer-c-BT2DRbCjzO-ImMvB_yElB6I

INT-1206 have the file/folder focus in the change explorer change the opened file in the diff view

---

intuita-webview/src/jobDiffView/App.tsx
intuita-webview/src/jobDiffView/DiffViewer/Container.tsx
intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
intuita-webview/src/jobDiffView/DiffViewer/index.tsx
intuita-webview/src/shared/types.ts
src/components/webview/webviewEvents.ts

I also removed not needed structures and props.

INT-1233 remove the Viewed checkbox from the diff view

---

intuita-webview/src/codemodList/App.tsx
intuita-webview/src/errors/App.tsx
intuita-webview/src/jobDiffView/App.tsx
src/components/webview/IntuitaPanelProvider.ts
src/components/webview/WebviewResolver.ts
src/components/webview/panelViewProps.ts
src/components/webview/webviewEvents.ts

Changes:
* remove the unused events like `afterWebviewMounted`
* added an event called `webview.setPanelViewProps`
* new (store-based) IntuitaPanelProvider
* added `PanelViewProps`
* added `selectViewProps`

INT-1234 introduce the new IntuitaPanelProvider

---

src/components/webview/IntuitaPanelProvider.ts
src/components/webview/panelViewProps.ts
src/components/webview/webviewEvents.ts
src/data/slice.ts
src/selectors/comparePersistedJobs.ts
src/selectors/selectExplorerTree.ts

Changes:
* allow incoming messages to the IntuitaPanelProvider
* pass the proper `jobIndex` for the panel's webview
* add a new incoming message: `webview.panel.changeJob` (to move jobs back and forth using the arrow buttons)

INT-1234 allow incoming messages to the IntuitaPanelProvider

---

src/data/slice.ts
src/persistedState/codecs.ts
src/persistedState/explorerNodeCodec.ts

Changes:
* added `_` at the beginning of the new explorer node structures to distinguish it from the old one
* added new actions for managing the explorer nodes

INT-1241 introduce new actions in the store

---

intuita-webview/src/fileExplorer/ActionsHeader/index.tsx
src/components/webview/CodemodListProvider.ts
src/extension.ts

[Screencast from 26.06.2023 13:48:41.webm](https://github.com/intuita-inc/intuita-vscode-extension/assets/35925521/ebee6b0f-055d-433b-b3f6-76b793070869)

INT-1241 show a warning when applying jobs during projection

---

intuita-webview/src/fileExplorer/ActionsFooter/index.tsx
intuita-webview/src/fileExplorer/App.tsx
src/extension.ts
src/selectors/selectExplorerTree.ts

- only seach projection is applied
- show N of files in apply button label

only search projection applied

---

intuita-webview/src/codemodList/CodemodNodeRenderer/index.tsx

remove the delay for the codemod discovery

remove delay

---

intuita-webview/src/campaignManager/App.tsx
intuita-webview/src/shared/TreeItem/index.tsx
src/cases/types.ts
src/components/engineService.ts
src/selectors/selectCodemodRunsTree.ts
src/selectors/selectMainWebviewViewProps.ts

add timestamp and popover to codemod run

---

src/data/slice.ts
src/persistedState/explorerNodeCodec.ts
src/selectors/selectExplorerTree.ts

keep tree struct

---

intuita-webview/src/main/App.tsx

allows to navigate tabs with keyboard
https://linear.app/intuita/issue/INT-1266/navigating-via-keyboard-arrow-between-panel-tabs-doesnt-work

Fix tab navigatoin

---

intuita-webview/src/fileExplorer/FileExplorerTreeNode.tsx
intuita-webview/src/fileExplorer/explorerNodeRenderer.tsx
intuita-webview/src/shared/TreeItem/index.tsx

https://linear.app/intuita/issue/INT-1298/indentation-of-files

fix files indent

---

src/components/messageBus.ts
src/components/webview/MainProvider.ts
src/data/slice.ts
src/data/storage.ts
src/extension.ts

- remove focusCodemod message, use store directly instead
- switch to codemods tab when focusing codemod

fix deeplink

---

intuita-webview/src/main/CodemodRuns.tsx
src/components/webview/MainProvider.ts
src/components/webview/webviewEvents.ts
src/data/slice.ts
src/persistedState/codecs.ts
src/selectors/selectMainWebviewViewProps.ts

This PR just stores the panel group positions, nothing more.

INT-1304 store panel group positions

---

intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
intuita-webview/src/codemodList/TreeView/ActionButton.tsx

INT-1284 Replace dry-run checkmark with play icon

---

src/components/engineService.ts
src/extension.ts
src/jobs/types.ts

- removes, oldDataPath, oldContentUri

remove unused job fields

---

intuita-webview/src/fileExplorer/explorerNodeRenderer.tsx
src/persistedState/explorerNodeCodec.ts
src/selectors/selectExplorerTree.ts

https://linear.app/intuita/issue/INT-1297/if-a-dir-is-a-leaf-show-how-many-files-recursively-were-applied-in

show how many files are applied

---

intuita-webview/src/codemodList/App.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/Directory.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/index.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/style.module.css
intuita-webview/src/codemodList/TreeView/ProgressBar.tsx
intuita-webview/src/codemodList/TreeView/index.tsx
intuita-webview/src/codemodList/components/style.module.css
intuita-webview/src/main/App.tsx

https://app.claap.io/intuita/make-codemod-discovery-panel-responsive-ui-c-BT2DRbCjzO-Pz-Ei22Yog-6

INT-1259 Make Codemod Discovery panel responsive UI

---

src/components/engineService.ts
src/data/slice.ts
src/persistedState/codecs.ts
src/selectors/selectExplorerTree.ts

Claap: https://app.claap.io/intuita/int-1317-allow-the-change-explorer-items-to-be-always-accessible-c-BT2DRbCjzO-GI1pMfVwOAR1

INT-1317 Allow the Change Explorer items to be always accessible

---

src/selectors/selectCodemodTree.ts

Update certified codemods

---

intuita-webview/src/jobDiffView/DiffViewer/Diff.tsx

we have tons of red squiggly lines in our diff view.

INT-1336 Don't use typescript for expected language

---

src/selectors/selectCodemodTree.ts

INT-1780 Sort codemods in discovery tab by name

---

intuita-webview/package.json
intuita-webview/src/jobDiffView/util.ts
intuita-webview/src/sourceControl/App.tsx
intuita-webview/src/sourceControl/CreateIssue/index.tsx
intuita-webview/src/sourceControl/CreateIssue/style.module.css
intuita-webview/src/sourceControl/index.css
intuita-webview/src/sourceControl/index.html
intuita-webview/src/sourceControl/index.tsx
intuita-webview/src/sourceControl/style.module.css
src/components/webview/IntuitaPanelProvider.ts
src/components/webview/SourceControlPanelProvider.ts
src/components/webview/sourceControlViewProps.ts
src/components/webview/webviewEvents.ts
src/data/slice.ts
src/extension.ts
src/persistedState/codecs.ts

- SourceControlPanelProvider
- CreateIssue view
claap: https://app.claap.io/intuita/int-1752-ui-for-gh-issue-creation-c-BT2DRbCjzO-mOjR_uzh5Ntg

INT-1752 UI for GH issue creation

---

cspell.json
intuita-webview/package.json
intuita-webview/pnpm-lock.yaml
intuita-webview/src/sourceControl/CreateIssue/index.tsx
intuita-webview/src/sourceControl/CreateIssue/style.module.css
intuita-webview/src/sourceControl/CreateIssue/tiptap.css

INT-1752 Use better editor

---

src/components/downloadService.ts
src/components/webview/SourceControlPanelProvider.ts
src/extension.ts
src/github/types.ts

- call `https://telemetry.intuita.io/sourceControl/github/issues` API request with title, body and repo
- after `html_url` is obtained, redirect user to the GH issue url
- type checking for API response

INT-1752 Integration 3

---

intuita-webview/src/CreateIssue/index.tsx

requested in https://app.claap.io/int-1752-ui-for-gh-issue-creation-c-BT2DRbCjzO-mOjR_uzh5Ntg#c-gJvCgHfAoF1K70jg4p-GN

rename title of GH issue creation

---

intuita-webview/src/CreateIssue/index.tsx
intuita-webview/src/CreateIssue/style.module.css
intuita-webview/src/main/App.tsx
src/components/webview/MainProvider.ts
src/extension.ts
src/persistedState/codecs.ts
src/selectors/selectMainWebviewViewProps.ts
src/selectors/selectSourceControlTabProps.ts

https://linear.app/intuita/issue/INT-1859/handle-invalid-access-token-from-cs-to-vsce
https://linear.app/intuita/issue/INT-1842/disable-create-issue-button-while-it-is-being-created-and-say-creating
- https://app.claap.io/intuita/disable-create-issue-button-while-it-is-being-created-and-say-creating-c-BT2DRbCjzO-CJDx7oLYjdcq

INT-1842 INT-1859 more improvements to report issue feature

---

intuita-webview/src/CreateIssue/index.tsx

claap: https://app.claap.io/intuita/ensure-that-the-syntax-highlight-of-languages-be-rendered-in-gh-c-BT2DRbCjzO-fKnJNUOwhgtp

INT-1853 Ensure that the syntax highlight of languages be rendered in GH

---

cspell.json
intuita-webview/src/CreateIssue/index.tsx
src/selectors/selectSourceControlTabProps.ts

claap: https://app.claap.io/intuita/int-1838-codeblock-containing-will-be-rendered-only-up-to-the-occurrence-of-this-very-character-c-BT2DRbCjzO-TonJVJwrbKc4

INT-1838 codeblock containing < , > will be rendered only up to the occurrence of this very character

---

intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx

INT-1869 change the icon/popup text for verified icon of codemods

---

intuita-webview/src/jobDiffView/DiffViewer/DiffItem.tsx
intuita-webview/src/jobDiffView/util.ts
src/components/engineService.ts
src/components/jobManager.ts
src/components/webview/IntuitaPanelProvider.ts
src/components/webview/panelViewProps.ts
src/components/webview/webviewEvents.ts
src/jobs/types.ts
src/persistedState/codecs.ts
src/selectors/selectSourceControlTabProps.ts

claap: https://app.claap.io/intuita/int-1837-fill-expected-code-snippet-in-gh-issue-via-report-issue-c-BT2DRbCjzO-48B2GAYq7_op

INT-1837 Fill "expected" code snippet in GH issue

---

package.json
src/components/webview/MainProvider.ts
src/extension.ts

claap: https://app.claap.io/intuita/int-1845-complete-auth-ux-with-ui-c-BT2DRbCjzO-DDxAN9mU0MtZ

INT-1845 Complete Auth UX with UI

---

package.json
src/extension.ts

claap: https://app.claap.io/intuita/int-1888-show-a-settings-icon-to-the-left-of-the-sign-in-sign-out-icon-c-BT2DRbCjzO-jWajzdwjbyjC

INT-1888 Show a settings icon to the left of the sign in/sign out icon

---

src/components/webview/IntuitaPanelProvider.ts

- When we switch between tabs, we close the diff view tab

INT-1903 Do not dispose diff view panel on tab switching

---

intuita-webview/src/codemodList/App.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
intuita-webview/src/main/App.css
intuita-webview/src/main/App.tsx
src/components/webview/MainProvider.ts
src/components/webview/webviewEvents.ts
src/data/slice.ts
src/extension.ts
src/persistedState/codecs.ts
src/selectors/selectMainWebviewViewProps.ts

claap: https://app.claap.io/intuita/use-custom-notifs-for-auth-flow-c-BT2DRbCjzO-Ud4kv8oT7yLo

INT-1898 Use custom notifs for auth flow

---

intuita-webview/src/codemodList/App.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
src/components/webview/MainProvider.ts
src/components/webview/webviewEvents.ts
src/extension.ts

INT-1904 Allow removing private codemod from registry

---

intuita-webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/index.tsx
intuita-webview/src/codemodList/CodemodNodeRenderer/style.module.css
intuita-webview/src/codemodList/TreeView/InfiniteProgress.module.css
intuita-webview/src/codemodList/TreeView/ProgressBar.tsx
src/components/engineService.ts

claap: https://app.claap.io/intuita/int-1922-implement-expandable-progressbar-container-and-replace-toaster-with-it-c-BT2DRbCjzO-hg5ZObr4hPEM

INT-1922 implement expandable progressbar container and replace toaster with it

---

intuita-webview/src/main/App.css
intuita-webview/src/main/CodemodRuns.tsx
package.json
pnpm-lock.yaml
src/commands/clearStateCommand.ts
src/components/webview/MainProvider.ts
src/data/slice.ts
src/extension.ts
src/persistedState/codecs.ts
src/selectors/selectMainWebviewViewProps.ts

https://github.com/intuita-inc/intuita-vscode-extension/assets/35925521/296486e5-f4ae-490b-9390-86e52863c018

feat: INT-2283 ensured discarded jobs do not reappear

---

intuita-webview/src/main/App.css
intuita-webview/src/main/App.tsx
src/components/webview/MainProvider.ts
src/selectors/selectMainWebviewViewProps.ts

INT-2373 do not initialize the VSCE if there is no active workspace

---

cspell.json
intuita-webview/package.json
package.json
src/components/bootstrapExecutablesService.ts
src/components/buildArguments.ts
src/components/engineService.ts
src/components/messageBus.ts
src/utilities.ts

https://app.claap.io/intuita/c-BT2DRbCjzO-8IF91qEU9YBz

Add Windows support to VSCE
